# Generated by Django 3.1.4 on 2020-12-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholder',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='City',
        ),
        migrations.AddField(
            model_name='shareholder',
            name='BusinessID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='EmailAddress',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='PaymentMode',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('CHEQUE', 'CHEQUE'), ('TRANSFER', 'TRANSFER')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='ShareHolderId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='ShareQty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='ShareValue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='UnitValue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='BankBankAccountNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='EmployeeNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
