# Generated by Django 3.1.4 on 2020-12-16 12:07

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20201216_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholder',
            name='Domicile',
        ),
        migrations.AddField(
            model_name='shareholder',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
