# Generated by Django 3.1.4 on 2020-12-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20201216_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
