# Generated by Django 3.1.4 on 2020-12-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20201216_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholder',
            name='entity',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('SOCIETY', 'SOCIETY'), ('CORPORATION', 'CORPORATION')], max_length=50, null=True),
        ),
    ]
