# Generated by Django 3.1.4 on 2020-12-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_shareholder_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='bank_account_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=40, null=True),
        ),
    ]
