# Generated by Django 3.1.4 on 2020-12-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20201216_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='birth_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='date_applied',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
