# Generated by Django 3.1.4 on 2020-12-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_auto_20201216_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
